### PR TITLE
Use the latest zipking release (2.14.0)

### PR DESCRIPTION
**Pull request by aerostitch**
Hi,

I would love to see the latest zipkin improvements in your aws-specific image.
Upgrading it in the Dockerfile to help get the thing going.

Thanks in advance,
Joseph

### CODE REVIEW

**Comment by adriancole** [comment]
hi! thanks for the help. Actually we are in process of preparing this for zipkin 2.14.1. There are some things that need to change in the zipkin-aws repo first.

**Comment by adriancole** [comment]
959bbe895c0259863542d09b25d398aa2a5cbbb3 is on the way now. thanks for the ping

**Comment by adriancole** [comment]
check openzipkin/zipkin-aws:0.17.1

**Comment by aerostitch** [comment]
Thanks!

**Pull request closed without merging**
